name: CI

on:
  push:
    branches: [ seed ]

jobs:

  get-inactive-users:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
            
        #run: cat $USERS_LIST | jq -r '[.[] | select(.isActive == false) | .login ] | join(",")' >> ./innactive-users-list.txt && cat ./innactive-users-list.txt
      - name: Build actions list string
        run: echo "actions_list=$(awk -vORS=, '{ print $1 }' actions-list.txt | sed 's/,$/\n/')" >> $GITHUB_ENV

      - name: Get Org Name
        run: echo "org_name=$(echo $GITHUB_REPOSITORY | awk -F "/" '{print $1}')" >> $GITHUB_ENV

      - name: Echo org_name
        run: echo "${{ env.org_name }}"
      
      - uses: octokit/request-action@v2.x
        id: set_approved_actions
        with:
          route: PUT /orgs/{org}/actions/permissions/selected-actions
          org: ${{ env.org_name }}
          github_owned_allowed: true
          patterns_allowed: [
            ${{ env.actions_list }}
          ],
          verified_allowed: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
